# Generated by Django 4.2.3 on 2023-08-07 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=50, verbose_name='Número de Documento')),
                ('tipoDocumento', models.CharField(choices=[('T.I.', 'Tarjeta de Identidad'), ('R.C.', 'Registro Civil'), ('C.E.', 'Cédula de Extranjería'), ('C.C.', 'Cédula de Ciudadania'), ('PASS', 'Pasaporte')], max_length=5, verbose_name='Tipo de Documento')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('programas', models.CharField(choices=[('Cuidarte', 'Cuidarte'), ('Alimentarte', 'Alimentarte'), ('Formarte', 'Formarte'), ('Impulsarte', 'Impulsarte'), ('Bienestar', 'Bienestar')], max_length=20, verbose_name='Programas')),
                ('genero', models.CharField(max_length=50, verbose_name='Género')),
                ('estadoUsuario', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Retirado', 'Retirado')], max_length=20, verbose_name='Estado del usuario')),
                ('fechaNacimiento', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de Nacimiento')),
                ('lugarNacimiento', models.CharField(max_length=50, verbose_name='Lugar de nacimiento')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono y/o celular')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=60, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=60, verbose_name='Apellidos')),
                ('foto', models.ImageField(blank=True, default='images/usuarios/default.png', upload_to='images/usuarios')),
                ('email', models.EmailField(max_length=150, verbose_name='Correo')),
                ('tipoDocumento', models.CharField(choices=[('C.C', 'Cédula de Ciudadanía'), ('C.E', 'Cédula de Extranjería'), ('T.I', 'Tarjeta de Identidad'), ('Otro', 'Otro Tipo de Documento')], default='C.C', max_length=4, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=50, verbose_name='Número de Documento')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(max_length=70, verbose_name='Dirección')),
                ('fecha_nacimiento', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha de Nacimiento')),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Empleado', 'Empleado')], default='Empleado', max_length=13, verbose_name='Rol')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Referencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=50, verbose_name='Número de Documento')),
                ('tipoDocumento', models.CharField(choices=[('T.I.', 'Tarjeta de Identidad'), ('R.C.', 'Registro Civil'), ('C.E.', 'Cédula de Extranjería'), ('C.C.', 'Cédula de Ciudadania'), ('PASS', 'Pasaporte')], max_length=5, verbose_name='Tipo de Documento')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('ocupacion', models.CharField(max_length=50, verbose_name='Ocupación')),
                ('relacion', models.CharField(max_length=50, verbose_name='Relación')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('tipoReferencia', models.CharField(choices=[('Personal', 'Personal'), ('Familiar', 'Familiar')], max_length=10, verbose_name='Tipo de Referencia')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.beneficiario', verbose_name='Beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Padrino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=50, verbose_name='Número de Documento')),
                ('tipoDocumento', models.CharField(choices=[('T.I.', 'Tarjeta de Identidad'), ('R.C.', 'Registro Civil'), ('C.E.', 'Cédula de Extranjería'), ('C.C.', 'Cédula de Ciudadania'), ('PASS', 'Pasaporte')], max_length=5, verbose_name='Tipo de Documento')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=50, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('correo', models.EmailField(max_length=50, verbose_name='Correo electrónico')),
                ('estado', models.BooleanField(default=False, verbose_name='Estado')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.beneficiario', verbose_name='Beneficiario')),
            ],
        ),
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.CharField(max_length=50, verbose_name='Número de Documento')),
                ('tipoDocumento', models.CharField(choices=[('T.I.', 'Tarjeta de Identidad'), ('R.C.', 'Registro Civil'), ('C.E.', 'Cédula de Extranjería'), ('C.C.', 'Cédula de Ciudadania'), ('PASS', 'Pasaporte')], max_length=5, verbose_name='Tipo de Documento')),
                ('nombres', models.CharField(max_length=50, verbose_name='Nombres y apellidos')),
                ('parentesco', models.CharField(max_length=50, verbose_name='Parentesco')),
                ('ocupacion', models.CharField(max_length=50, verbose_name='Ocupación')),
                ('direccion', models.CharField(max_length=50, verbose_name='Dirección')),
                ('barrio', models.CharField(max_length=50, verbose_name='Barrio y localidad')),
                ('telefono', models.CharField(max_length=50, verbose_name='Teléfono')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.beneficiario', verbose_name='Beneficiario')),
            ],
        ),
    ]
