# Generated by Django 4.2.3 on 2024-01-19 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padrino',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='referencia',
            name='estado',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(max_length=16, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(max_length=16, verbose_name='Nombres'),
        ),
    ]
