# Generated by Django 4.2.3 on 2024-01-31 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_padrino_estado_remove_referencia_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='padrino',
            name='ocupacion',
            field=models.CharField(default='ocupacion', max_length=20, verbose_name='Ocupación'),
        ),
    ]
