# Generated by Django 4.2.3 on 2024-02-09 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_padrino_ocupacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padrino',
            name='ocupacion',
            field=models.CharField(max_length=20, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=8, verbose_name='Estado'),
        ),
    ]
